In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
df=pd.read_clipboard()
df

    序号           项目名称
0    1          蓝牙工程车
1    2      硬纸盒端盖折叠装置
2    3       电控无碳小车制作
3    4          微型雕刻机
4    5        多轴复合加工机
5    6        液态介质巡逻机
6    7         螺旋升降平台
7    8        小型压力测试机
8    9        双摇杆搬运机构
9   10         槽轮机构演示
10  11         温度响应滑台
11  12        X、Y运动平台
12  13          发球计数器
13  14       小型飞行器牵引车
14  15       公交车门启闭装置
15  16     一种带传动的供料装置
16  17         自动绘图装置
17  18    二自由度角度随动机械手
18  19    奶牛场环境监控模拟装置
19  20         交换平台机构
20  21          机械臂控制
21  22            机械臂
22  23  飞行升力的控制以及数值显示

In [3]:
type(df)

pandas.core.frame.DataFrame

In [4]:
df.columns

Index(['序号', '项目名称'], dtype='object')

In [8]:
df.项目名称

0             蓝牙工程车
1         硬纸盒端盖折叠装置
2          电控无碳小车制作
3             微型雕刻机
4           多轴复合加工机
5           液态介质巡逻机
6            螺旋升降平台
7           小型压力测试机
8           双摇杆搬运机构
9            槽轮机构演示
10           温度响应滑台
11          X、Y运动平台
12            发球计数器
13         小型飞行器牵引车
14         公交车门启闭装置
15       一种带传动的供料装置
16           自动绘图装置
17      二自由度角度随动机械手
18      奶牛场环境监控模拟装置
19           交换平台机构
20            机械臂控制
21              机械臂
22    飞行升力的控制以及数值显示
Name: 项目名称, dtype: object

In [9]:
type(df['序号'])

pandas.core.series.Series

In [12]:
new_df=DataFrame(df,columns=["序号",'项目名称','test'])
new_df

    序号           项目名称  test
0    1          蓝牙工程车   NaN
1    2      硬纸盒端盖折叠装置   NaN
2    3       电控无碳小车制作   NaN
3    4          微型雕刻机   NaN
4    5        多轴复合加工机   NaN
5    6        液态介质巡逻机   NaN
6    7         螺旋升降平台   NaN
7    8        小型压力测试机   NaN
8    9        双摇杆搬运机构   NaN
9   10         槽轮机构演示   NaN
10  11         温度响应滑台   NaN
11  12        X、Y运动平台   NaN
12  13          发球计数器   NaN
13  14       小型飞行器牵引车   NaN
14  15       公交车门启闭装置   NaN
15  16     一种带传动的供料装置   NaN
16  17         自动绘图装置   NaN
17  18    二自由度角度随动机械手   NaN
18  19    奶牛场环境监控模拟装置   NaN
19  20         交换平台机构   NaN
20  21          机械臂控制   NaN
21  22            机械臂   NaN
22  23  飞行升力的控制以及数值显示   NaN

In [13]:
new_df['test']=np.arange(0,23)

In [14]:
new_df

    序号           项目名称  test
0    1          蓝牙工程车     0
1    2      硬纸盒端盖折叠装置     1
2    3       电控无碳小车制作     2
3    4          微型雕刻机     3
4    5        多轴复合加工机     4
5    6        液态介质巡逻机     5
6    7         螺旋升降平台     6
7    8        小型压力测试机     7
8    9        双摇杆搬运机构     8
9   10         槽轮机构演示     9
10  11         温度响应滑台    10
11  12        X、Y运动平台    11
12  13          发球计数器    12
13  14       小型飞行器牵引车    13
14  15       公交车门启闭装置    14
15  16     一种带传动的供料装置    15
16  17         自动绘图装置    16
17  18    二自由度角度随动机械手    17
18  19    奶牛场环境监控模拟装置    18
19  20         交换平台机构    19
20  21          机械臂控制    20
21  22            机械臂    21
22  23  飞行升力的控制以及数值显示    22

In [15]:
df['序号']

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
Name: 序号, dtype: int64

In [16]:
df.iterrows()

In [18]:
for row in df.iterrows():
    print(row[0],row[1])

0 序号          1
项目名称    蓝牙工程车
Name: 0, dtype: object
1 序号              2
项目名称    硬纸盒端盖折叠装置
Name: 1, dtype: object
2 序号             3
项目名称    电控无碳小车制作
Name: 2, dtype: object
3 序号          4
项目名称    微型雕刻机
Name: 3, dtype: object
4 序号            5
项目名称    多轴复合加工机
Name: 4, dtype: object
5 序号            6
项目名称    液态介质巡逻机
Name: 5, dtype: object
6 序号           7
项目名称    螺旋升降平台
Name: 6, dtype: object
7 序号            8
项目名称    小型压力测试机
Name: 7, dtype: object
8 序号            9
项目名称    双摇杆搬运机构
Name: 8, dtype: object
9 序号          10
项目名称    槽轮机构演示
Name: 9, dtype: object
10 序号          11
项目名称    温度响应滑台
Name: 10, dtype: object
11 序号           12
项目名称    X、Y运动平台
Name: 11, dtype: object
12 序号         13
项目名称    发球计数器
Name: 12, dtype: object
13 序号            14
项目名称    小型飞行器牵引车
Name: 13, dtype: object
14 序号            15
项目名称    公交车门启闭装置
Name: 14, dtype: object
15 序号              16
项目名称    一种带传动的供料装置
Name: 15, dtype: object
16 序号          17
项目名称    自动绘图装置
Name: 16, dtype: object
17 序号               18
项目名称    二自由度角度随动机械手
Name: 17, dtype: object
18 序号               19
项目名称    奶牛场环境监控模拟装置
Name: 18, dtype: object
19 序号          20
项目名称    交换平台机构
Name: 19, dtype: object
20 序号         21
项目名称    机械臂控制
Name: 20, dtype: object
21 序号       22
项目名称    机械臂
Name: 21, dtype: object
22 序号                 23
项目名称    飞行升力的控制以及数值显示
Name: 22, dtype: object

In [19]:
df2=pd.read_clipboard()

In [20]:
df2

   Name:            20,  dtype:  object
0     21             序号      22    None
1   项目名称            机械臂    None    None
2  Name:            21,  dtype:  object
3     22             序号      23    None
4   项目名称  飞行升力的控制以及数值显示    None    None
5  Name:            22,  dtype:  object

In [23]:
df2=df2

In [24]:
df2

           0     1       2     3              4       5
Name:     21  项目名称   Name:    22           项目名称   Name:
20,       序号   机械臂     21,    序号  飞行升力的控制以及数值显示     22,
dtype:    22  None  dtype:    23           None  dtype:
object  None  None  object  None           None  object

# dataframe IO

In [25]:
df2.to_clipboard()

In [26]:
df2.to_csv("df2.csv")

In [27]:
new_df.to_json()

'{"\\u5e8f\\u53f7":{"0":1,"1":2,"2":3,"3":4,"4":5,"5":6,"6":7,"7":8,"8":9,"9":10,"10":11,"11":12,"12":13,"13":14,"14":15,"15":16,"16":17,"17":18,"18":19,"19":20,"20":21,"21":22,"22":23},"\\u9879\\u76ee\\u540d\\u79f0":{"0":"\\u84dd\\u7259\\u5de5\\u7a0b\\u8f66","1":"\\u786c\\u7eb8\\u76d2\\u7aef\\u76d6\\u6298\\u53e0\\u88c5\\u7f6e","2":"\\u7535\\u63a7\\u65e0\\u78b3\\u5c0f\\u8f66\\u5236\\u4f5c","3":"\\u5fae\\u578b\\u96d5\\u523b\\u673a","4":"\\u591a\\u8f74\\u590d\\u5408\\u52a0\\u5de5\\u673a","5":"\\u6db2\\u6001\\u4ecb\\u8d28\\u5de1\\u903b\\u673a","6":"\\u87ba\\u65cb\\u5347\\u964d\\u5e73\\u53f0","7":"\\u5c0f\\u578b\\u538b\\u529b\\u6d4b\\u8bd5\\u673a","8":"\\u53cc\\u6447\\u6746\\u642c\\u8fd0\\u673a\\u6784","9":"\\u69fd\\u8f6e\\u673a\\u6784\\u6f14\\u793a","10":"\\u6e29\\u5ea6\\u54cd\\u5e94\\u6ed1\\u53f0","11":"X\\u3001Y\\u8fd0\\u52a8\\u5e73\\u53f0","12":"\\u53d1\\u7403\\u8ba1\\u6570\\u5668","13":"\\u5c0f\\u578b\\u98de\\u884c\\u5668\\u7275\\u5f15\\u8f66","14":"\\u516c\\u4ea4\\u8f66\\u95e8\\u542f\\u95ed\\u88c5\\u7f6e","15":"\\u4e00\\u79cd\\u5e26\\u4f20\\u52a8\\u7684\\u4f9b\\u6599\\u88c5\\u7f6e","16":"\\u81ea\\u52a8\\u7ed8\\u56fe\\u88c5\\u7f6e","17":"\\u4e8c\\u81ea\\u7531\\u5ea6\\u89d2\\u5ea6\\u968f\\u52a8\\u673a\\u68b0\\u624b","18":"\\u5976\\u725b\\u573a\\u73af\\u5883\\u76d1\\u63a7\\u6a21\\u62df\\u88c5\\u7f6e","19":"\\u4ea4\\u6362\\u5e73\\u53f0\\u673a\\u6784","20":"\\u673a\\u68b0\\u81c2\\u63a7\\u5236","21":"\\u673a\\u68b0\\u81c2","22":"\\u98de\\u884c\\u5347\\u529b\\u7684\\u63a7\\u5236\\u4ee5\\u53ca\\u6570\\u503c\\u663e\\u793a"},"test":{"0":0,"1":1,"2":2,"3":3,"4":4,"5":5,"6":6,"7":7,"8":8,"9":9,"10":10,"11":11,"12":12,"13":13,"14":14,"15":15,"16":16,"17":17,"18":18,"19":19,"20":20,"21":21,"22":22}}'

In [29]:
new_df.to_html("new_df.html")